version: '3'
services:
  neo4j:
    image: neo4j:5.2.0
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_dbms_allow__upgrade=true
